name: Publish Bicep Package
on: workflow_dispatch
jobs:
  create-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: bicep-package
          path: range
        id: package

      - name: print artefact url
        run: |
            echo ${{ steps.package.outputs.artifact-url}}

      - name: Trigger target workflow with parameter
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/Yuvaraj-Devaraj/github-edg-pipelines/actions/workflows/dev-deploy-workflow.yml/dispatches \
            -d '{"ref":"main", "inputs": {"github_package_url": "${{ steps.package.outputs.artifact-url}}", "github_artefact_id": "${{ steps.package.outputs.artifact-id}}", "github_caller_workflow_run_id": "${{github.run_id}}", "github_sha_id": "${{github.sha}}", "github_workflow_name": "${{github.workflow}}", "github_repository_name": "${{github.repository}}" }}'

  set-package-sha-level:
    runs-on: ubuntu-latest
    needs: [create-package]
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: set variable value
        run: |
          gh variable set PackageSHALevel --body ${{github.sha}}