name: Publish Bicep Package
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Publish Biceps
        run: |
          echo "Hi hello!"
          echo ${GITHUB_WORKSPACE}
          echo "-------------"
          ls ${GITHUB_WORKSPACE}

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: edg-range-integration-bicep-package
          path: ${GITHUB_WORKSPACE}/range